### ISSUE TITLE
content of basket is lost when switching between multiple ticket

### ISSUE THREAD

**Issue by Gregoire-Lesmainsdansleguidon** [ScilCoop/pasteque-android#2]
I create a ticket for Customer 1, add some product, 
Customer 2 arrives, i create a new ticket with some other product, 
if i switch back to Customer 1 without closing Customer 2 and then back to Customer 2 then content all tickets are lost.
(tickets remains, but content is lost)

**Comment by nsvir** [comment]
Thanks for the report.
Can you provide more informations ?
- is your Synchronization is configured Manually or Automatically ?
- I guess your tickets mode is Standard ?
- Does this scenario happen everytime ?

**Comment by Gregoire-Lesmainsdansleguidon** [comment]
Hi @nsvir 
I am currently out for a few days, 
be back next thursday.  I will re-do the full test and give you all the infos.

**Comment by Gregoire-Lesmainsdansleguidon** [comment]
Hi, 
synchronisation is configured manually
ticket mode is standard, 

and magic ! the bug does not appears.

I think that synchro used to be configured automatically when the bug was reported, 
and someone advised me to configure it manually, but i did not make the test since that date.

for me it is closed now !

sorry for the false reporting.

Regards, 

Grégoire.
