### ISSUE TITLE
adding new customer : touching outside the form kills the forms

### ISSUE THREAD

**Issue by Gregoire-Lesmainsdansleguidon** [ScilCoop/pasteque-android#6]
when adding a new Customer, the "save" button is hidden by the keyboard, 
when clicking outside the popup to make the keyboard disapear, the popup closes and the form is lost.

1/ touching outside the form by mistake closes the form and loose all the content !
2/ saving requires presssing 'next' 5 time until keyboard disapear showing the 'save' button.

**Comment by nsvir** [comment]
The problem has been solved, it will be available in the next release.
In your current version, you can press the android back button to manually dismiss the active keyboard.

**Comment by Gregoire-Lesmainsdansleguidon** [comment]
great
